# Site Information

name: Digital Humanities Research Institute
description: Digital Humanities Research Institute
url: dhinstitutes.org
title: Digital Humanities Research Institute
host-institution: the Graduate Center, CUNY
host-institution-url: https://www.gc.cuny.edu
date-range: June 11-20, 2018
apply-link: 
author:
  name: GC Digital Initiatives
  email: info@dhinstitutes.org
  url: https://gcdi.commons.gc.cuny.edu/
  twitter: Digital_Fellows
  github: http://github.com/GCDigitalFellows
  address: Digital Scholarship Lab, Room 7414<br>The Graduate Center, CUNY<br>365 Fifth Avenue<br />New York, NY 10016<br>
  description: GC Digital Initiatives builds and sustains an active community around the shared idea of a "Digital GC," where scholars and technologists explore new modes of inquiry that thoughtfully integrate digital tools and methods into the research, teaching, and service missions of the institution. Learn more on our <a href="https://gcdi.commons.gc.cuny.edu/about/">website</a>.




# link-reference should be one short, descriptive word
courses:
  - name: Command Line
    url: https://github.com/DHRI-Curriculum/command-line
    link-reference: terminal
    description: Introduction to the UNIX command line. Topics covered will include navigating the filesystem, manipulating the environment, executing useful commands, and using pipes to communicate between programs. This session will teach you how to communicate directly with your computerâ€™s operating system using a text-based interface and is a useful first step in learning many other technical skills.
  - name: Git
    url: https://github.com/DHRI-Curriculum/git
    link-reference: git
    description: Git is a tool for managing changes to a set of files. It allows users to access open source repositories, recover earlier versions of a project, and collaborate with other contributors. This session will be beneficial to anyone working with data, code, or text.
  - name: Python
    url: https://github.com/DHRI-Curriculum/python
    link-reference:  python
    description: Python is a programming language that can be used for a wide range of tasks, including collecting and analyzing data in a variety of formats, building web applications, and much more. It is likely the most popular language for academic researchers because of its flexibility and adaptability.
  - name: Databases
    url: https://github.com/DHRI-Curriculum/databases
    link-reference: databases
    description: Databases are invaluable tools for organization and are better than a spreadsheet for working with multiple data sets, asking questions, and adding structure to your data. SQL is a programming language for working with databases. This workshop will introduce you to the basics of SQL, and will include hands-on practice creating databases and tables, importing data, and querying the database.
  - name: Text Analysis
    url: https://github.com/DHRI-Curriculum/text-analysis
    link-reference: text
    description: This session will introduce text analysis and text classification in Python using The Natural Language Toolkit (NLTK) library and scikit-learn. Through attending this session, you will learn how to use Python to analyze large amounts of text (i.e., literary works, social media corpora, etc.) to find word frequencies, collocations, and learn the basics of text classification with machine learning. This session is designed for researchers who work with various forms of text-based data.
  - name: Mapping
    url: https://github.com/DHRI-Curriculum/mapping
    link-reference: mapping
    description: This session introduces simple yet powerful ways of displaying spatial information through CartoDB and QGIS. This session will be of particular interest both to researchers working with spatial information as well as anyone interested in storytelling with maps.
  - name: Machine Learning 
    url: https://github.com/DHRI-Curriculum/machine-learning
    link-reference: ml
    description: Machine learning is an application of artificial intelligence (AI) that provides systems the ability to automatically learn and improve from experience without being explicitly programmed.
  - name: HTML & CSS
    url: https://github.com/DHRI-Curriculum/html-css
    link-reference: html
    description: Modern web pages are created using HTML to control content, CSS to control appearance, and JavaScript to dictate behavior. This session will be helpful for anyone that wants to build on the web.
  - name: Twitter API
    url: https://github.com/DHRI-Curriculum/twitter-api
    link-reference: twitter
    description: This session will cover the basics of accessing data via the Twitter API. including specific challenges that arise when working with large, text-based data sets. This session will be beneficial for anyone who wants to collect data from Twitter or other social networks.
  - name: Digital Ethics
    url: https://github.com/DHRI-Curriculum/ethics
    link-reference: ethics
    description: A discussion of digital ethics with an emphasis on social justice, transparency, and accessibility.

# this tells Jekyll to build the site in the "docs"
# directory, which is ideal for hosting by GitHub Pages
destination: docs


# Files that won't be included in the compiled version of the site
exclude:
  - '*.sh'
  - CNAME
  - bower_components
  - node_modules
  - _images
  - '.*'
  - 'gulpfile.js'
  - 'build_vendor.js'
  - 'get_data.js'
  - 'README.md'

# _config.stage.yml overwrites these options when you run locally
future: false
limit_posts: 10 # Only make the last 10 posts so generating isn't slow
show_drafts: false

#required by github-pages
lsi: false # Disables the more accurate related posts
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

# Permalink structure and pagination options
# permalink: pretty
# paginate: 10
# paginate_path: 'page:num'
# excerpt_separator: '<!--more-->'
